spring:
  application:
    name: clearflow-website-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/name
    username: username
    password: password
    name: name
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true

  mvc:
    problemdetails:
      enabled: true

app:
  owner:
    email: email
    password: password

  jwt:
    issuer: clearflow-backend
    access-cookie-name: ACCESS_TOKEN
    refresh-cookie-name: REFRESH_TOKEN

    access-secret: access-secret
    refresh-secret: refresh-secret
    access-ttl-seconds: 1209600
    refresh-ttl-seconds: 5184000
    cookie-secure: false

  crypto:
    key-version: v1
    aes-key: aes-key

  storage:
    local-root: storage/uploads
    max-photo-bytes: 5242880

  ozon:
    base-url: https://api-seller.ozon.ru
    connect-timeout-seconds: 5
    read-timeout-seconds: 10

  cors:
    allowed-origins:
      - "https://example.com"
      - "https://www.example.com"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
    allow-credentials: true

    swagger:
      title: "API"
      description: "Документация API"
      version: "0.1.0"

      servers:
        - url: "http://localhost:8080"
          description: "Local Dev Server"
        - url: "https://api.example.com"
          description: "Production Server"